HashSyntax:
  Description: >
                 Use Ruby 1.8 hash syntax { :a => 1, :b => 2 }.
                 We need to support older system ruby installations.
  EnforcedStyle: hash_rockets
  Enabled: true
